let navs = [{
    "clmid": "1",
    "spclmid": "0",
    "ordno": "1",
    "c_level": "1",
    "clmcode": "index",
    "clmname": "系统首页",
    "clmurl": "",
    "prname": "",
    "en": "1",
    "show": "1",
    "grouplist": "2,5",
    "memo": "",
    "icon": "icon-home",
    "childs": [
        {
            "clmid": "11",
            "spclmid": "0",
            "ordno": "0",
            "c_level": "2",
            "clmcode": "icon-home",
            "clmname": "系统首页",
            "clmurl": "/",
            "prname": null,
            "en": "1",
            "show": "1",
            "grouplist": "2,5",
            "memo": null,
            "icon": "icon-home"
        },
    ]
}, {
    "clmid": "2",
    "spclmid": "0",
    "ordno": "1",
    "c_level": "1",
    "clmcode": "index",
    "clmname": "用户管理",
    "clmurl": "",
    "prname": "",
    "en": "1",
    "show": "1",
    "grouplist": "2,5",
    "memo": "",
    "clicon": "front_icon",
    "childs": [
        {
            "clmid": "21",
            "spclmid": "0",
            "ordno": "0",
            "c_level": "2",
            "clmcode": "front_index",
            "clmname": "消费者管理",
            "clmurl": "/yhgl",
            "prname": null,
            "en": "1",
            "show": "1",
            "grouplist": "2,5",
            "memo": null,
            "clicon": "home_icon"
        }, {
            "clmid": "22",
            "spclmid": "0",
            "ordno": "0",
            "c_level": "2",
            "clmcode": "front_index",
            "clmname": "mock模拟数据",
            "clmurl": "/mockPage",
            "prname": null,
            "en": "1",
            "show": "1",
            "grouplist": "2,5",
            "memo": null,
            "clicon": "home_icon"
        }, {
            "clmid": "23",
            "spclmid": "0",
            "ordno": "0",
            "c_level": "2",
            "clmcode": "front_index",
            "clmname": "图表页面",
            "clmurl": "/chart",
            "prname": null,
            "en": "1",
            "show": "1",
            "grouplist": "2,5",
            "memo": null,
            "clicon": "home_icon"
        },
    ]
},
    {
        "clmid": "3",
        "spclmid": "0",
        "ordno": "1",
        "c_level": "1",
        "clmcode": "index",
        "clmname": "EVA",
        "clmurl": "",
        "prname": "",
        "en": "1",
        "show": "1",
        "grouplist": "2,5",
        "memo": "",
        "clicon": "front_icon",
        "childs": [
            {
                "clmid": "31",
                "spclmid": "0",
                "ordno": "0",
                "c_level": "2",
                "clmcode": "front_index",
                "clmname": "时间面板",
                "clmurl": "/timePage",
                "prname": null,
                "en": "1",
                "show": "1",
                "grouplist": "2,5",
                "memo": null,
                "clicon": "home_icon"
            },
            {
                "clmid": "32",
                "spclmid": "0",
                "ordno": "0",
                "c_level": "2",
                "clmcode": "front_index",
                "clmname": "小状态面板",
                "clmurl": "/handPage",
                "prname": null,
                "en": "1",
                "show": "1",
                "grouplist": "2,5",
                "memo": null,
                "clicon": "home_icon"
            }, {
                "clmid": "32",
                "spclmid": "0",
                "ordno": "0",
                "c_level": "2",
                "clmcode": "front_index",
                "clmname": "雷达面板",
                "clmurl": "/radarPage",
                "prname": null,
                "en": "1",
                "show": "1",
                "grouplist": "2,5",
                "memo": null,
                "clicon": "home_icon"
            },{
                "clmid": "33",
                "spclmid": "0",
                "ordno": "0",
                "c_level": "2",
                "clmcode": "front_index",
                "clmname": "警告",
                "clmurl": "/warningPage",
                "prname": null,
                "en": "1",
                "show": "1",
                "grouplist": "2,5",
                "memo": null,
                "clicon": "home_icon"
            },
        ]
    },
    {
        "clmid": "4",
        "spclmid": "0",
        "ordno": "1",
        "c_level": "1",
        "clmcode": "index",
        "clmname": "业务管理",
        "clmurl": "",
        "prname": "",
        "en": "1",
        "show": "1",
        "grouplist": "2,5",
        "memo": "",
        "clicon": "front_icon",
        "childs": [
            {
                "clmid": "41",
                "spclmid": "0",
                "ordno": "0",
                "c_level": "2",
                "clmcode": "front_index",
                "clmname": "任务查询",
                "clmurl": "/rwcx",
                "prname": null,
                "en": "1",
                "show": "1",
                "grouplist": "2,5",
                "memo": null,
                "clicon": "home_icon"
            },
            {
                "clmid": "42",
                "spclmid": "0",
                "ordno": "0",
                "c_level": "2",
                "clmcode": "front_index",
                "clmname": "分级查询",
                "clmurl": "/fjcx",
                "prname": null,
                "en": "1",
                "show": "1",
                "grouplist": "2,5",
                "memo": null,
                "clicon": "home_icon"
            },
        ]
    },
    {
        "clmid": "5",
        "spclmid": "0",
        "ordno": "1",
        "c_level": "1",
        "clmcode": "index",
        "clmname": "系统管理",
        "clmurl": "",
        "prname": "",
        "en": "1",
        "show": "1",
        "grouplist": "2,5",
        "memo": "",
        "clicon": "front_icon",
        "childs": [
            {
                "clmid": "51",
                "spclmid": "0",
                "ordno": "0",
                "c_level": "2",
                "clmcode": "front_index",
                "clmname": "系统消息",
                "clmurl": "/news",
                "prname": null,
                "en": "1",
                "show": "1",
                "grouplist": "2,5",
                "memo": null,
                "clicon": "home_icon"
            },
            {
                "clmid": "52",
                "spclmid": "0",
                "ordno": "0",
                "c_level": "2",
                "clmcode": "front_index",
                "clmname": "基本设置",
                "clmurl": "/basic",
                "prname": null,
                "en": "1",
                "show": "1",
                "grouplist": "2,5",
                "memo": null,
                "clicon": "home_icon"
            }, {
                "clmid": "53",
                "spclmid": "0",
                "ordno": "0",
                "c_level": "2",
                "clmcode": "front_index",
                "clmname": "密码修改",
                "clmurl": "/pwd",
                "prname": null,
                "en": "1",
                "show": "1",
                "grouplist": "2,5",
                "memo": null,
                "clicon": "home_icon"
            },
        ]
    },
    {
        "clmid": "6",
        "spclmid": "0",
        "ordno": "1",
        "c_level": "1",
        "clmcode": "index",
        "clmname": "常用页面",
        "clmurl": "",
        "prname": "",
        "en": "1",
        "show": "1",
        "grouplist": "2,5",
        "memo": "",
        "clicon": "front_icon",
        "childs": [
            {
                "clmid": "61",
                "spclmid": "0",
                "ordno": "0",
                "c_level": "2",
                "clmcode": "front_index",
                "clmname": "关于我们",
                "clmurl": "/aboutUs",
                "prname": null,
                "en": "1",
                "show": "1",
                "grouplist": "2,5",
                "memo": null,
                "clicon": "home_icon"
            },
            {
                "clmid": "62",
                "spclmid": "0",
                "ordno": "0",
                "c_level": "2",
                "clmcode": "front_index",
                "clmname": "404",
                "clmurl": "/404",
                "prname": null,
                "en": "1",
                "show": "1",
                "grouplist": "2,5",
                "memo": null,
                "clicon": "home_icon"
            },
        ]
    },

];

export default navs;
